// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplateLibraryInventory = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "securitySchemes": {
            "BearerAuth": {
                "in": "header",
                "name": "Authorization",
                "type": "apiKey"
            }
        }
    },
    "info": {
        "contact": {
            "email": "juergen.enge@unibas.ch",
            "name": "Jürgen Enge",
            "url": "https://ub.unibas.ch"
        },
        "description": "{{escape .Description}}",
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "termsOfService": "http://swagger.io/terms/",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/ping": {
            "get": {
                "description": "for testing if server is running",
                "operationId": "get-ping",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {
                                        "type": "string"
                                    },
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "does ping",
                "tags": [
                    "libraryinventory"
                ]
            }
        }
    },
    "openapi": "3.1.0"
}`

// SwaggerInfoLibraryInventory holds exported Swagger Info so clients can modify it
var SwaggerInfoLibraryInventory = &swag.Spec{
	Version:          "1.0",
	Title:            "Library Inventory API",
	Description:      "for testing if server is running",
	InfoInstanceName: "LibraryInventory",
	SwaggerTemplate:  docTemplateLibraryInventory,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoLibraryInventory.InstanceName(), SwaggerInfoLibraryInventory)
}
